### ISSUE TITLE
请问有考虑支持TGI的接口吗

### ISSUE THREAD

**Issue by zhangzq1011** [deanxv/gpt-content-audit#1]
huggingface-text-generation-inference

<img width="1189" alt="image" src="https://github.com/user-attachments/assets/0134ce43-020d-429b-8252-5e570726d67c">

**Comment by deanxv** [comment]
项目本身不支持，但是可以利用其他项目间接支持吧，比如[api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm)

**Comment by zhangzq1011** [comment]
> 项目本身不支持，但是可以利用其他项目间接支持吧，比如[api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm)

我在本地扩展了tgi的对话接口，看是否需要合并
