### ISSUE TITLE
在运行一段时间后出现全部请求超时，后台日志报错500

### ISSUE THREAD

**Issue by gkingt** [deanxv/gpt-content-audit#2]
**温馨提示: 未`star`项目会被自动关闭issue哦!**

**例行检查**

+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我理解并愿意跟进此 issue,协助测试和提供反馈
+ [ ] 我理解并认可上述内容,并理解项目维护者精力有限,不遵循规则的 issue 可能会被无视或直接关闭

**问题描述**
在运行一段时间后出现全部请求超时，后台日志报错500，使用的转发newapi正常，审核用的始皇oaipro正常，但是后台日志500，包括获取模型接口也是500,具体原因未知，因为没有更多日志可以查看
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/91116b47-4594-41fe-8e0e-3e7a88d764cd)

如果没有的话,请删除此节。

**Comment by deanxv** [comment]
可以[TG联系我](https://t.me/alaneast)并提供你的环境变量让我本地调试排查吗？
